CREATE TABLE EMPLOYEE (
    ID VARCHAR(36) NOT NULL,
    FIRST_NAME VARCHAR(255) NOT NULL,
    LAST_NAME VARCHAR(255) NOT NULL,
    NUMBER_OF_DEPENDENTS NUMERIC NOT NULL DEFAULT 0,
    HEIGHT NUMERIC(1000, 2) NOT NULL DEFAULT 0.0,
    WEIGHT NUMERIC(1000, 2) NOT NULL DEFAULT 0.0,
    HIRED_DATE DATE NOT NULL,
    START_TIME TIME NOT NULL,
    IS_REGULAR BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (ID)
);
